In [1]:
from tensorflow.keras.datasets import imdb

In [3]:
(train_data, train_label), (test_data, test_label) = imdb.load_data(num_words = 10000)

17464789/17464789 ━━━━━━━━━━━━━━━━━━━━ 4s 0us/step


In [4]:
train_data.head()

AttributeError: 'numpy.ndarray' object has no attribute 'head'

In [5]:
print(train_data)

[list([1, 14, 22, 16, 43, 530, 973, 1622, 1385, 65, 458, 4468, 66, 3941, 4, 173, 36, 256, 5, 25, 100, 43, 838, 112, 50, 670, 2, 9, 35, 480, 284, 5, 150, 4, 172, 112, 167, 2, 336, 385, 39, 4, 172, 4536, 1111, 17, 546, 38, 13, 447, 4, 192, 50, 16, 6, 147, 2025, 19, 14, 22, 4, 1920, 4613, 469, 4, 22, 71, 87, 12, 16, 43, 530, 38, 76, 15, 13, 1247, 4, 22, 17, 515, 17, 12, 16, 626, 18, 2, 5, 62, 386, 12, 8, 316, 8, 106, 5, 4, 2223, 5244, 16, 480, 66, 3785, 33, 4, 130, 12, 16, 38, 619, 5, 25, 124, 51, 36, 135, 48, 25, 1415, 33, 6, 22, 12, 215, 28, 77, 52, 5, 14, 407, 16, 82, 2, 8, 4, 107, 117, 5952, 15, 256, 4, 2, 7, 3766, 5, 723, 36, 71, 43, 530, 476, 26, 400, 317, 46, 7, 4, 2, 1029, 13, 104, 88, 4, 381, 15, 297, 98, 32, 2071, 56, 26, 141, 6, 194, 7486, 18, 4, 226, 22, 21, 134, 476, 26, 480, 5, 144, 30, 5535, 18, 51, 36, 28, 224, 92, 25, 104, 4, 226, 65, 16, 38, 1334, 88, 12, 16, 283, 5, 16, 4472, 113, 103, 32, 15, 16, 5345, 19, 178, 32])
 list([1, 194, 1153, 194, 8255, 78, 228, 5, 6, 1463, 

In [16]:
import numpy as np
def vectorize_sequences(sequences, dimensions = 10000):
 results = np.zeros((len(sequences), dimensions))
 for i,sequences in enumerate(sequences):
     results[i, sequences] = 1
 return results
x_train = vectorize_sequences(train_data)
x_test = vectorize_sequences(test_data)

In [10]:
print(x_train)

[[0. 1. 1. ... 0. 0. 0.]
 [0. 1. 1. ... 0. 0. 0.]
 [0. 1. 1. ... 0. 0. 0.]
 ...
 [0. 1. 1. ... 0. 0. 0.]
 [0. 1. 1. ... 0. 0. 0.]
 [0. 1. 1. ... 0. 0. 0.]]


In [17]:
y_train = np.asarray(train_label).astype('float32')
y_test = np.asarray(test_label).astype('float32')

In [18]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
model = Sequential()
model.add(Dense(16, input_shape=(10000, ), activation = "relu"))
model.add(Dense(16, activation = "relu"))
model.add(Dense(1, activation = "sigmoid"))

model.compile(optimizer='adam', loss = 'mse', metrics = ['accuracy'])

model.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ dense_3 (Dense)                      │ (None, 16)                  │         160,016 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_4 (Dense)                      │ (None, 16)                  │             272 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_5 (Dense)                      │ (None, 1)                   │              17 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 160,305 (626.19 KB)

 Trainable params: 160,305 (626.19 KB)

 Non-trainable params: 0 (0.00 B)

In [19]:
history = model.fit(x_train, y_train, validation_split = 0.3, epochs = 20, verbose =1, batch_size = 512)


Epoch 1/20
35/35 ━━━━━━━━━━━━━━━━━━━━ 20s 336ms/step - accuracy: 0.7601 - loss: 0.1785 - val_accuracy: 0.8716 - val_loss: 0.1123
Epoch 2/20
35/35 ━━━━━━━━━━━━━━━━━━━━ 3s 83ms/step - accuracy: 0.9061 - loss: 0.0819 - val_accuracy: 0.8916 - val_loss: 0.0849
Epoch 3/20
35/35 ━━━━━━━━━━━━━━━━━━━━ 4s 46ms/step - accuracy: 0.9399 - loss: 0.0553 - val_accuracy: 0.8939 - val_loss: 0.0805
Epoch 4/20
35/35 ━━━━━━━━━━━━━━━━━━━━ 4s 101ms/step - accuracy: 0.9572 - loss: 0.0405 - val_accuracy: 0.8907 - val_loss: 0.0810
Epoch 5/20
35/35 ━━━━━━━━━━━━━━━━━━━━ 1s 32ms/step - accuracy: 0.9715 - loss: 0.0298 - val_accuracy: 0.8883 - val_loss: 0.0839
Epoch 6/20
35/35 ━━━━━━━━━━━━━━━━━━━━ 1s 33ms/step - accuracy: 0.9806 - loss: 0.0225 - val_accuracy: 0.8833 - val_loss: 0.0869
Epoch 7/20
35/35 ━━━━━━━━━━━━━━━━━━━━ 1s 38ms/step - accuracy: 0.9874 - loss: 0.0167 - val_accuracy: 0.8815 - val_loss: 0.0898
Epoch 8/20
35/35 ━━━━━━━━━━━━━━━━━━━━ 2s 45ms/step - accuracy: 0.9904 - loss: 0.0130 - val_accuracy: 0.8784 

In [20]:
model.evaluate(x_test, y_test)
model.predict(x_test)

782/782 ━━━━━━━━━━━━━━━━━━━━ 7s 8ms/step - accuracy: 0.8572 - loss: 0.1171
782/782 ━━━━━━━━━━━━━━━━━━━━ 6s 6ms/step


array([[0.26224244],
       [0.9999738 ],
       [0.01702576],
       ...,
       [0.242848  ],
       [0.00189087],
       [0.0731252 ]], shape=(25000, 1), dtype=float32)